services:
  postgres:
    image: postgres:15
    container_name: mygamelist-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mygamelist
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
