version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: testdb
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    volumes:
      - postgres-data-test:/var/lib/postgresql/data

volumes:
  postgres-data-test:
